### ISSUE TITLE
the decode() function for headers['subject'] always return NULL value

### ISSUE THREAD

**Issue by pupleh4t** [gdgbhu/gmail-php-starter#3]
the decode() function for headers['subject'] always return NULL value. I checked using var_dump without 'headers' filtering. 'mimeSubject' didn't contain 'Subject' in 'headers' array. Could you help me, please? Thanks

**Comment by muffycompo** [comment]
What was the output of you var_dump?

**Comment by pupleh4t** [comment]
if I change in gmail.php to :
...  
$mimeSubject = $mimeDecode->decode();
var_dump($mimeSubject);
...

the output looks like this:
object(stdClass)#29 (3) { ["headers"]=> array(1) { ["delivered-to"]=> string(32) -hidden-} ["ctype_primary"]=> string(4) "text" ["ctype_secondary"]=> string(5) "plain" } 

There is no 'subject' in headers.

**Comment by muffycompo** [comment]
This is strange...is it possible that the particular email in question does not have a subject?

**Comment by pupleh4t** [comment]
No, actually it has a subject. If I var_dump from dcMessage, the output looks like this:

string(5227) "Delivered-To: hermawan.rahmat.h@mail.ugm.ac.id Received: by 10.202.230.81 with SMTP id d78csp912480oih; Sat, 2 May 2015 07:36:35 -0700 (PDT) X-Received: by 10.180.208.42 with SMTP id mb10mr5148771wic.80.1430577395164; Sat, 02 May 2015 07:36:35 -0700 (PDT) Return-Path: Received: from o4.sgmail.github.com (o4.sgmail.github.com. [192.254.112.99]) by mx.google.com with ESMTPS id j8si2822205wia.40.2015.05.02.07.36.32 for (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128); Sat, 02 May 2015 07:36:35 -0700 (PDT) Received-SPF: none (google.com: bounces+848413-de93-hermawan.rahmat.h=mail.ugm.ac.id@sgmail.github.com does not designate permitted sender hosts) client-ip=192.254.112.99; Authentication-Results: mx.google.com; spf=none (google.com: bounces+848413-de93-hermawan.rahmat.h=mail.ugm.ac.id@sgmail.github.com does not designate permitted sender hosts) smtp.mail=bounces+848413-de93-hermawan.rahmat.h=mail.ugm.ac.id@sgmail.github.com; dkim=pass header.i=@github.com; dmarc=pass (p=NONE dis=NONE) header.from=github.com DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; s=s20150108; bh=N3PMt0/XylG4t8ot+yCe7nsiM9Q=; b=kQQZQi1Cv02s5tZ1 hfLzpl9B0lTm4DppAH3HLr74wODa6hrc/cfbMbO6Dk3oR24ZHfbvFbl5sKmt+WPG yNRSnNxh+MAv9DO1UXihkJdReBjD6WaBFYZotf0ao6RL/p/S48c3A5FIod5JD2jS R1VkwPc22RfmRxaCzlpKUJ5g/gc= Received: by filter0161p1mdw1.sendgrid.net with SMTP id filter0161p1mdw1.2154.5544E0DDA 2015-05-02 14:36:13.599500043 +0000 UTC Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17]) by ismtpd-031 (SG) with ESMTP id 14d150e615a.5b19.185852 for ; Sat, 02 May 2015 14:36:13 +0000 (UTC) Date: Sat, 02 May 2015 07:36:13 -0700 From: Mfawa Alfred Onen Reply-To: gdgbhu/gmail-php-starter To: gdgbhu/gmail-php-starter Cc: pupleh4t Message-ID: In-Reply-To: References: Subject: Re: [gmail-php-starter] the decode() function for headers['subject'] always return NULL value (#3) Mime-Version: 1.0 Content-Type: multipart/alternative; boundary="--==_mimepart_5544e0dd63428_78333fd4429c92c0691c5"; charset=UTF-8 Content-Transfer-Encoding: 7bit Precedence: list X-GitHub-Sender: muffycompo X-GitHub-Recipient: pupleh4t X-GitHub-Reason: author List-ID: gdgbhu/gmail-php-starter List-Archive: https://github.com/gdgbhu/gmail-php-starter List-Post: List-Unsubscribe: , X-Auto-Response-Suppress: All X-GitHub-Recipient-Address: hermawan.rahmat.h@mail.ugm.ac.id X-SG-EID: uaakkdWZMVpKUtOH6RxC9jbzH6oumj9o0ntODSKfiV1Nu/b6iLDJT27gN0hDjPYiRj227cDinUPDnd jhHoQPIYyMqeVj2TlxbAONC35Te+4PsdWctHy+Y6mURdR4Q8/GEGx2xW7dNqGtc5w7EB5Pzo3Z5bLb duq57CLl/Liz4pKb1eKQov8xFivbiS77xOBZ ----==_mimepart_5544e0dd63428_78333fd4429c92c0691c5 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 7bit This is strange...is it possible that the particular email in question does not have a subject? --- Reply to this email directly or view it on GitHub: https://github.com/gdgbhu/gmail-php-starter/issues/3#issuecomment-98365601 ----==_mimepart_5544e0dd63428_78333fd4429c92c0691c5 Content-Type: text/html; charset=UTF-8 Content-Transfer-Encoding: 7bit
This is strange...is it possible that the particular email in question does not have a subject?

—
Reply to this email directly or view it on GitHub.

----==_mimepart_5544e0dd63428_78333fd4429c92c0691c5-- " 

Is this sensitive information? If yes, I will delete soon.

**Comment by pupleh4t** [comment]
No, actually it has a subject. I check from dcMessage, a part of the output still contain the subject string. Thanks.

**Comment by muffycompo** [comment]
Yeah, when sending such information, just remove real email and IP address.
This line seems to be weird: "In-Reply-To: References: Subject"

**Comment by pupleh4t** [comment]
Well, I'm sorry for didn't know about sharing information ethics. 
So... Is there a solution for that? I try to understand your decode() code but it's beyond from my knowledge. haha.

**Comment by muffycompo** [comment]
Its ok, no problem, let me try it out and get back to you.

**Comment by pupleh4t** [comment]
Thanks a lot

**Comment by muffycompo** [comment]
I have added some PHP extension dependency (php mailparse) and now use a different Mime Mail Parse wrapper. Try it and let me know if it works for you as it did for me.

**Comment by pupleh4t** [comment]
I got another error. The error message is "Fatal error: Call to undefined function mailparse_msg_create() in C:\xampp\htdocs\DemoAPI3\vendor\php-mime-mail-parser\php-mime-mail-parser\src\Parser.php on line 123" 
Neither xampp nor wamp, php mailparse didn't work for me.

**Comment by muffycompo** [comment]
You need to install or enable the php_mailparse extension in you php.ini
file first. It was stated in the PHP requirements section.

**Comment by pupleh4t** [comment]
Actually, I have trouble with installing php mailparser and pcel dependencies. Can you give me an easy tutorial, please?

**Comment by gdgbhu** [comment]
​Check this out
http://wiki.cerbweb.com/Installing_PHP_Mailparse#On_Windows-based_Servers_.28XAMPP.29

**Comment by pupleh4t** [comment]
It's working now. Thanks.

**Comment by muffycompo** [comment]
Great. I am closing the issue now.
